### ISSUE TITLE
config files location?

### ISSUE THREAD

**Issue by im7FFY** [regolith-linux/regolith-i3blocks#2]
As the titile says, I'm not able to find the config files location, I searched in the usual location (used i3blocks before) and found nothing :/ . Might be simple to resolve but I prefer to wait for some feedback before tweaking/breaking? everything.

**Comment by kgilmer** [comment]
Hi @im7FFY !  The configuration file Regolith uses for i3blocks is at `/etc/i3blocks.conf`.  There are some additional blocks available in `/usr/share/i3blocks` but be prepared to update the colors yourself, as I've only themed the blocks that Regolith enables by default.  Additionally, there is [work underway](https://github.com/regolith-linux/regolith-desktop/issues/24) to extract all color theme information into Xresources so this stuff may change.

If you mangle something in i3 beyond repair you can simply remove the `~/.config/i3-regolith/config` file, log out and a fresh default copy will be put back there.

**Comment by kgilmer** [comment]
Closing, reopen if there is still an issue.
